import aspcol.kernelinterpolation.kernel as ki
import numpy as np


def reconstruct_multisrc(krr_params, pos_output, pos_data, wave_num, kernel_func, kernel_args):
    num_freq = wave_num.shape[0]
    kernel_matrix = kernel_func(pos_output, pos_data, wave_num, *kernel_args)

    reconstructed = np.squeeze(kernel_matrix @ krr_params[:,:,None], axis=-1)
    reconstructed = np.reshape(reconstructed, (num_freq, pos_output.shape[0], -1))
    reconstructed = np.moveaxis(reconstructed, 1, 2)
    return reconstructed

def get_krr_params_multisrc(data, pos, wave_num, reg_param, kernel_func, kernel_args):
    """Calculates the optimal KRR parameters for the standard kernel interpolation problem with multiple sources.

    Parameters
    ----------
    data : ndarray of shape (num_freq, num_measurements). 
        IMPORTANT: the data first has the measurements for pos[:,0] for all sources that was measured there,
        then the data for pos[:,1] and so on. 
        num_measurements is somewhere between num_pos and num_pos * num_src, 
        depending on how many sources were measured at each position.
    pos : ndarray of shape (num_pos, 3)
        the positions of all measurements where at least one source was measured
    src_idx : ndarray of shape (num_src, num_pos) with boolean values
        indicates whether that source was measured at that position. 
    wave_num : ndarray of shape (num_freq)
    reg_param : float
        positive value to regularize the problem. Corresponds to lambda in the optimization problem. 
    kernel_func : callable
        with calling signature kernel_func(pos1, pos2, *kernel_args)
        should return ndarray (..., num_pos1, num_pos2)
    kernel_args : list
        extra arguments that are needed for the kernel function

    Returns
    -------
    a : ndarray of shape (num_freq, num_measurements)
        The optimal KRR parameters for the given data and kernel.
    """
    num_measurements = data.shape[-1]
    kernel_matrix = kernel_func(pos, pos, wave_num, *kernel_args)

    K_reg = kernel_matrix + reg_param * np.eye(num_measurements)[None,:,:]
    a = np.linalg.solve(K_reg, data)
    return a

def kernel_multisrc_crossdir(pos1, pos2, wave_num, src_idx1, src_idx2, src_weighting, directions, beta):
    """Kernel for joint estimation of a multisource sound field with non-diagonal directional weighting
    
    Parameters
    ----------
    pos1 : ndarray of shape (num_pos1, 3)
    pos2 : ndarray of shape (num_pos2, 3)
    wave_num : ndarray of shape (num_freq)
        wave numbers for the frequencies of interest, defined as 2*pi*f/c
    src_idx1 : ndarray of shape (num_src, num_pos1) with boolean values
        For each position m in pos1, the value in src_idx1[s,m] indicates whether the source s was measured there
    src_idx2 : ndarray of shape (num_src, num_pos2) with boolean values
        For each position n in pos2, the value in src_idx2[s,n] indicates whether the source s was measured there
    src_weighting : optional, ndarray of shape (num_freq, num_src, num_src)
        The weighting of the sources for each frequency. This is in some sense a measure of 
        similarity between the sound fields generated by the sources. If not given, this is 
        assumed to be the identity matrix, which corresponds to the standard kernel where each source
        is treated independently. 
    base_kernel : optional, callable
        The base kernel function to use. If not given, this defaults to the diffuse Helmholtz kernel.
        Pick any single-frequency kernel in the kernelinterpolation module.
    base_kernel_args : optional, list
        The arguments to pass to the base kernel function, if required. 

    Returns
    -------
    full_kernel_matrix : ndarray of shape (num_freq, num_params1, num_params2)
        The kernel matrix for the given positions and sources. num_params1 and num_params2 are the number of parameters
        which can be calculated as sum(src_idx1) and sum(src_idx2) respectively. This should be exactly the total
        number of measurements in total. 
    """

    num_freq = wave_num.shape[0]
    num_src = src_idx1.shape[0]
    assert num_src == src_idx2.shape[0]

    num_pos1 = pos1.shape[0]
    num_pos2 = pos2.shape[0]
    num_params1 = np.sum(src_idx1).astype(int)
    num_params2 = np.sum(src_idx2).astype(int) 
    
    assert np.array(beta).ndim == 0

    dir_matrix = directions[:,None,:] + directions[None,:,:]
    dir_matrix /= 2
    dir_matrix[np.arange(directions.shape[0]), np.arange(directions.shape[0])] *= 2
    dir_vec = dir_matrix.reshape(-1,3)

    kernel_vals = ki.kernel_directional(pos1, pos2, wave_num, dir_vec, beta)

    kernel_vals = kernel_vals.reshape((num_freq, num_src, num_src, num_pos1, num_pos2))

    full_kernel_matrix = np.zeros((num_freq, num_params1, num_params2), dtype=np.complex128)
    S_m = np.cumsum(np.concatenate(([0], np.sum(src_idx1, axis=0))))
    S_n = np.cumsum(np.concatenate(([0], np.sum(src_idx2, axis=0))))
    for m in range(num_pos1):
        for n in range(num_pos2):
            P_m = _src_idx_to_projection(src_idx1[:,m])
            P_n = _src_idx_to_projection(src_idx2[:,n])

            #kernel_diag = np.eye(num_src)[None,:,:] * kernel_vals[:,None,:,m,n]
            #kernel_block = src_weighting_sqrt @ kernel_diag @ np.moveaxis(src_weighting_sqrt, 1,2).conj()
            kernel_block = kernel_vals[:,:,:,m,n]

            #kernel_block = kernel_vals[:,:,None,m,n] * src_weighting # corresponds to K @ B where K is diagonal and B is the weighting
            kernel_block = P_m[None,:,:] @ kernel_block @ P_n.T[None,:,:]

            full_kernel_matrix[:, S_m[m]:S_m[m+1], S_n[n]:S_n[n+1]] = kernel_block

    return full_kernel_matrix



def kernel_multisrc(pos1, pos2, wave_num, src_idx1, src_idx2, src_weighting = None, base_kernel = None, base_kernel_args = None):
    """General kernel for joint estimation of a multisource sound field.
    
    Parameters
    ----------
    pos1 : ndarray of shape (num_pos1, 3)
    pos2 : ndarray of shape (num_pos2, 3)
    wave_num : ndarray of shape (num_freq)
        wave numbers for the frequencies of interest, defined as 2*pi*f/c
    src_idx1 : ndarray of shape (num_src, num_pos1) with boolean values
        For each position m in pos1, the value in src_idx1[s,m] indicates whether the source s was measured there
    src_idx2 : ndarray of shape (num_src, num_pos2) with boolean values
        For each position n in pos2, the value in src_idx2[s,n] indicates whether the source s was measured there
    src_weighting : optional, ndarray of shape (num_freq, num_src, num_src)
        The weighting of the sources for each frequency. This is in some sense a measure of 
        similarity between the sound fields generated by the sources. If not given, this is 
        assumed to be the identity matrix, which corresponds to the standard kernel where each source
        is treated independently. 
    base_kernel : optional, callable
        The base kernel function to use. If not given, this defaults to the diffuse Helmholtz kernel.
        Pick any single-frequency kernel in the kernelinterpolation module.
    base_kernel_args : optional, list
        The arguments to pass to the base kernel function, if required. 

    Returns
    -------
    full_kernel_matrix : ndarray of shape (num_freq, num_params1, num_params2)
        The kernel matrix for the given positions and sources. num_params1 and num_params2 are the number of parameters
        which can be calculated as sum(src_idx1) and sum(src_idx2) respectively. This should be exactly the total
        number of measurements in total. 
    """

    num_freq = wave_num.shape[0]
    num_src = src_idx1.shape[0]
    assert num_src == src_idx2.shape[0]

    num_pos1 = pos1.shape[0]
    num_pos2 = pos2.shape[0]
    num_params1 = np.sum(src_idx1).astype(int)
    num_params2 = np.sum(src_idx2).astype(int) 
    
    if base_kernel is None:
        base_kernel = ki.kernel_diffuse
    if base_kernel_args is None:
        base_kernel_args = []
    if src_weighting is None:
        src_weighting = np.eye(num_src)[None,:,:]

    #src_weighting_sqrt = np.linalg.cholesky(src_weighting)
    #src_weighting_sqrt = np.stack([splin.sqrtm(src_weighting[i,:,:]) for i in range(src_weighting.shape[0])], axis=0)

    #rng = np.random.default_rng(2345654)
    #U = spstats.unitary_group.rvs(src_weighting.shape[1], random_state=rng)
    #src_weighting_sqrt = np.stack([src_weighting_sqrt[i,:,:] @ U for i in range(src_weighting.shape[0])], axis=0)

    kernel_vals = base_kernel(pos1, pos2, wave_num, *base_kernel_args)
    if kernel_vals.ndim == 3:
        kernel_vals = kernel_vals[:,None,:,:]

    full_kernel_matrix = np.zeros((num_freq, num_params1, num_params2), dtype=np.complex128)
    S_m = np.cumsum(np.concatenate(([0], np.sum(src_idx1, axis=0))))
    S_n = np.cumsum(np.concatenate(([0], np.sum(src_idx2, axis=0))))
    for m in range(num_pos1):
        for n in range(num_pos2):
            P_m = _src_idx_to_projection(src_idx1[:,m])
            P_n = _src_idx_to_projection(src_idx2[:,n])

            kernel_diag = np.eye(num_src)[None,:,:] * kernel_vals[:,None,:,m,n]
            kernel_block = src_weighting @ kernel_diag @ np.moveaxis(src_weighting, 1,2).conj()

            #kernel_block = kernel_vals[:,:,None,m,n] * src_weighting # corresponds to K @ B where K is diagonal and B is the weighting
            kernel_block = P_m[None,:,:] @ kernel_block @ P_n.T[None,:,:]

            full_kernel_matrix[:, S_m[m]:S_m[m+1], S_n[n]:S_n[n+1]] = kernel_block

    return full_kernel_matrix


def kernel_multisrc_diffuse(pos1, pos2, wave_num, src_idx1, src_idx2):
    """Diffuse kernel for joint estimation of a multisource sound field.
    
    Parameters
    ----------
    pos1 : ndarray of shape (num_pos1, 3)
    pos2 : ndarray of shape (num_pos2, 3)
    wave_num : ndarray of shape (num_freq)
        wave numbers for the frequencies of interest, defined as 2*pi*f/c
    src_idx1 : ndarray of shape (num_src, num_pos1) with boolean values
        For each position m in pos1, the value in src_idx1[s,m] indicates whether the source s was measured there
    src_idx2 : ndarray of shape (num_src, num_pos2) with boolean values
        For each position n in pos2, the value in src_idx2[s,n] indicates whether the source s was measured there
    src_weighting : ndarray of shape (num_freq, num_src, num_src)
        The weighting of the sources for each frequency. This is in some sense a measure of 
        similarity between the sound fields generated by the sources.

    Returns
    -------
    full_kernel_matrix : ndarray of shape (num_freq, num_params1, num_params2)
        The kernel matrix for the given positions and sources. num_params1 and num_params2 are the number of parameters
        which can be calculated as sum(src_idx1) and sum(src_idx2) respectively. This should be exactly the total
        number of measurements in total. 
    """
    return kernel_multisrc(pos1, pos2, wave_num, src_idx1, src_idx2)

def _src_idx_to_projection(src_idx_col):
    prototype = np.eye(src_idx_col.shape[0])
    P = prototype[src_idx_col,:]
    return P


def kernel_multisrc_src_weighted(pos1, pos2, wave_num, src_idx1, src_idx2, src_weighting):
    """Kernel for joint estimation of a multisource sound field with non-identity source weighting.

    Parameters
    ----------
    pos1 : ndarray of shape (num_pos1, 3)
    pos2 : ndarray of shape (num_pos2, 3)
    wave_num : ndarray of shape (num_freq)
        wave numbers for the frequencies of interest, defined as 2*pi*f/c
    src_idx1 : ndarray of shape (num_src, num_pos1) with boolean values
        For each position m in pos1, the value in src_idx1[s,m] indicates whether the source s was measured there
    src_idx2 : ndarray of shape (num_src, num_pos2) with boolean values
        For each position n in pos2, the value in src_idx2[s,n] indicates whether the source s was measured there
    src_weighting : ndarray of shape (num_freq, num_src, num_src)
        The weighting of the sources for each frequency. This is in some sense a measure of 
        similarity between the sound fields generated by the sources.

    Returns
    -------
    full_kernel_matrix : ndarray of shape (num_freq, num_params1, num_params2)
        The kernel matrix for the given positions and sources. num_params1 and num_params2 are the number of parameters
        which can be calculated as sum(src_idx1) and sum(src_idx2) respectively. This should be exactly the total
        number of measurements in total. 
    """
    return kernel_multisrc(pos1, pos2, wave_num, src_idx1, src_idx2, src_weighting)


def kernel_multisrc_directional(pos1, pos2, wave_num, src_idx1, src_idx2, directions, beta):
    """Kernel for joint estimation of a multisource sound field with non-identity source weighting and directional weighting.

    Uses the von-mises fisher distribution to model the directional weighting, which gives a closed form solution for the kernel.
    This means that only a single direction can be promoted for each source. 

    Parameters
    ----------
    pos1 : ndarray of shape (num_pos1, 3)
    pos2 : ndarray of shape (num_pos2, 3)
    wave_num : ndarray of shape (num_freq)
        wave numbers for the frequencies of interest, defined as 2*pi*f/c
    src_idx1 : ndarray of shape (num_src, num_pos1) with boolean values
        For each position m in pos1, the value in src_idx1[s,m] indicates whether the source s was measured there
    src_idx2 : ndarray of shape (num_src, num_pos2) with boolean values
        For each position n in pos2, the value in src_idx2[s,n] indicates whether the source s was measured there
    src_weighting : ndarray of shape (num_freq, num_src, num_src)
        The weighting of the sources for each frequency. This is in some sense a measure of 
        similarity between the sound fields generated by the sources.
    directions : ndarray of shape (num_src, 3)
        The directions of the sources.
    beta : non-negative ndarray of shape (num_src,)
        The concentration parameter for the von-mises fisher distribution.

    Returns
    -------
    full_kernel_matrix : ndarray of shape (num_freq, num_params1, num_params2)
        The kernel matrix for the given positions and sources. num_params1 and num_params2 are the number of parameters
        which can be calculated as sum(src_idx1) and sum(src_idx2) respectively. This should be exactly the total
        number of measurements in total. 
    """
    return kernel_multisrc(pos1, pos2, wave_num, src_idx1, src_idx2, base_kernel=ki.kernel_directional, base_kernel_args=[directions, beta])

def kernel_multisrc_src_weighted_directional(pos1, pos2, wave_num, src_idx1, src_idx2, src_weighting, directions, beta):
    """Kernel for joint estimation of a multisource sound field with non-identity source weighting and directional weighting.

    Uses the von-mises fisher distribution to model the directional weighting, which gives a closed form solution for the kernel.
    This means that only a single direction can be promoted for each source. 

    Parameters
    ----------
    pos1 : ndarray of shape (num_pos1, 3)
    pos2 : ndarray of shape (num_pos2, 3)
    wave_num : ndarray of shape (num_freq)
        wave numbers for the frequencies of interest, defined as 2*pi*f/c
    src_idx1 : ndarray of shape (num_src, num_pos1) with boolean values
        For each position m in pos1, the value in src_idx1[s,m] indicates whether the source s was measured there
    src_idx2 : ndarray of shape (num_src, num_pos2) with boolean values
        For each position n in pos2, the value in src_idx2[s,n] indicates whether the source s was measured there
    src_weighting : ndarray of shape (num_freq, num_src, num_src)
        The weighting of the sources for each frequency. This is in some sense a measure of 
        similarity between the sound fields generated by the sources.
    directions : ndarray of shape (num_src, 3)
        The directions of the sources.
    beta : non-negative ndarray of shape (num_src,)
        The concentration parameter for the von-mises fisher distribution.

    Returns
    -------
    full_kernel_matrix : ndarray of shape (num_freq, num_params1, num_params2)
        The kernel matrix for the given positions and sources. num_params1 and num_params2 are the number of parameters
        which can be calculated as sum(src_idx1) and sum(src_idx2) respectively. This should be exactly the total
        number of measurements in total. 
    """
    return kernel_multisrc(pos1, pos2, wave_num, src_idx1, src_idx2, src_weighting, ki.kernel_directional, [directions, beta])

def kernel_multisrc_diffuse_simple(pos1, pos2, wave_num, src_idx):
    """
    
    src_idx : ndarray of shape (num_src, num_pos) with boolean values
    """
    kernel_vals = ki.kernel_diffuse(pos1, pos2, wave_num)

    num_freq = wave_num.shape[0]
    num_src = src_idx.shape[0]

    num_pos1 = pos1.shape[0]
    num_pos2 = pos2.shape[0]

    if not np.all(src_idx):
        raise NotImplementedError("Not implemented for sources that were not measured at all positions")
    num_params1 = num_pos1 * num_src
    num_params2 = num_pos2 * num_src

    full_kernel_matrix = np.zeros((num_freq, num_params1, num_params2), dtype=np.complex128)

    for m in range(num_pos1):
        for n in range(num_pos2):
            full_kernel_matrix[:, m*num_src:(m+1)*num_src, n*num_src:(n+1)*num_src] = np.eye(num_src)[None,:,:] * kernel_vals[:,m:m+1,n:n+1]
    return full_kernel_matrix

def kernel_multisrc_src_weighted_simple(pos1, pos2, wave_num, src_idx, src_weighting):
    """
    
    src_idx : ndarray of shape (num_src, num_pos) with boolean values

    src_weighting : ndarray of shape (num_freq, num_src, num_src)
    """
    kernel_vals = ki.kernel_diffuse(pos1, pos2, wave_num)

    num_freq = wave_num.shape[0]
    num_src = src_idx.shape[0]

    num_pos1 = pos1.shape[0]
    num_pos2 = pos2.shape[0]

    if not np.all(src_idx):
        raise NotImplementedError("Not implemented for sources that were not measured at all positions")
    num_params1 = num_pos1 * num_src
    num_params2 = num_pos2 * num_src

    full_kernel_matrix = np.zeros((num_freq, num_params1, num_params2), dtype=np.complex128)

    for m in range(num_pos1):
        for n in range(num_pos2):
            full_kernel_matrix[:,m*num_src:(m+1)*num_src,n*num_src:(n+1)*num_src] = src_weighting * kernel_vals[:,m:m+1,n:n+1]
    return full_kernel_matrix

